version: '3.8'
services:
  minecraft:
    container_name: minecraft
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - './:/app'
    working_dir: '/app'
    ports:
      - '8000:8000'
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LAMBDA_START_URL=${LAMBDA_START_URL}
      - LAMBDA_STOP_URL=${LAMBDA_STOP_URL}
      - GUILD_ID=${GUILD_ID}
    restart: unless-stopped
